-- Run this in the Supabase SQL Editor.
-- It creates the contact form table and allows public form submissions.

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

drop policy if exists "Allow public contact form submissions" on public.contact_submissions;

create policy "Allow public contact form submissions"
on public.contact_submissions
for insert
to anon
with check (
  full_name <> ''
  and email <> ''
  and message <> ''
);
